# -*- coding: utf-8 -*-
"""Proiect2FrincuAlexandru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VW_YLDr6jaRERLR5j_vRSo7WedCr_sfl
"""

# conectare gdrive
from google.colab import drive
drive.mount('/content/drive')
base_dir = '/content/drive/MyDrive/Proiect_ML/chest_xray'
train_dir = base_dir + '/train'

# import lb deep learn
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import matplotlib.pyplot as plt
import os

# verif nr poze folder antrenament
print(f"Am găsit {len(os.listdir(train_dir + '/NORMAL'))} imagini Normale și {len(os.listdir(train_dir + '/PNEUMONIA'))} cu Pneumonie în Train.")

# pregatim imagini & augmentam
# variam pozele ca sa nu le memoreze
datagen = ImageDataGenerator(
    rescale=1./255,          # Normalizare (aducem pixelii între 0 și 1)
    validation_split=0.2,    # 20% pentru testare
    rotation_range=15,       # rotim usor pozele
    zoom_range=0.2,          # marim pe detalii
    width_shift_range=0.1,   # miscam orizontal
    height_shift_range=0.1   # miscam vertical
)

# invatare 80%
train_data = datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='binary',     # 0 = normal, 1 = pneumonia
    subset='training'
)

# testare 20%
val_data = datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

# echilibrare date (pe normal sa fie de 4 ori mai imp)
weights = {0: 4.0, 1: 1.0}

#  CNN
model = Sequential([
    # filtreaza formele de baza si micsoreaza poza pe esential
    Conv2D(32, (3,3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D(2, 2),

    # detectare detalii complexe ( ex. pete/acumulari lichid)
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2, 2),

    # ptr detalii mai fine
    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2, 2),

    Flatten(), # lista de date pt procesare
    Dense(128, activation='relu'), # corelam datele
    Dropout(0.5), # ne asiguram ca nu toceste pozele
    Dense(1, activation='sigmoid') # clasificam binar 0/1
])

# optimizam antrenarea cu o viteza mai mica
optimizator = Adam(learning_rate=0.0001)
model.compile(optimizer=optimizator, loss='binary_crossentropy', metrics=['accuracy'])

# oprire daca nu mai e progres, evitam overfitting
callback_oprire = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
# reducem viteza la final pt precizie mai mare
callback_viteza = ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3)

# train
print("\nÎncepem antrenarea rețelei...")
history = model.fit(
    train_data,
    epochs=30,
    validation_data=val_data,
    class_weight=weights,
    callbacks=[callback_oprire, callback_viteza]
)

# graf
plt.plot(history.history['accuracy'], label='Acuratețe Învățare', color='blue')
plt.plot(history.history['val_accuracy'], label='Acuratețe Validare (Test)', color='orange')
plt.title('Evoluția Învățării Rețelei CNN (Optimizat)')
plt.xlabel('Epoca (Trecerea prin date)')
plt.ylabel('Acuratețe (0 la 1)')
plt.legend()
plt.grid(True)

# salvare in gdrive
plt.savefig('/content/drive/MyDrive/Proiect_ML/grafic_rezultate.png')
model.save('/content/drive/MyDrive/Proiect_ML/model_pneumonie.keras')
print("Modelul optimizat și graficul au fost salvate în Drive!")
plt.show()